#
python3 journal_eingabe_neu.py 22.12.2022 'Python programmieren, Hannover - Erding fahren, Sandra nach Erding gekommen' '' '' ''
python3 journal_eingabe_neu.py 23.12.2022 'Python und postgres' '' '' ''
python3 journal_eingabe_neu.py 24.12.2022 'ED - Gambach fahren' '' '' ''
python3 journal_eingabe_neu.py 25.12.2022 ' ' '' '' ''
python3 journal_eingabe_neu.py 26.12.2022 'Gambach - Köln fahren' '' '' ''
python3 journal_eingabe_neu.py 27.12.2022 'Python und postgres' '' '' ''
python3 journal_eingabe_neu.py 28.12.2022 'einkaufen, Roseline Sex' '' '' ''
python3 journal_eingabe_neu.py 29.12.2022 'Python und Postgres' '' '' ''
python3 journal_eingabe_neu.py 30.12.2022 'Python und Postgres, Visual Studio Code in Git' '' ''  ''
python3 journal_eingabe_neu.py 31.12.2022 'Python und Postgres, Visual Studio Code in Git' '' '' ''
python3 journal_eingabe_neu.py 01.01.2023 'Köln nach Erding fahren, Roseline WoZi Sex' '' '' ''
python3 journal_eingabe_neu.py 02.01.2023 'Python, Postgrers, Visual Studio Code auf MacBook, Forstner Essen Wartenbaerg Stütz, Katzenbuckel, seizliche Übungen, situps' '' ''
python3 journal_eingabe_neu.py 03.01.2023 'Python, VSCode auf Macbook Air' '' '' ''
python3 journal_eingabe_neu.py 04.01.2023 'Termin Standesamt' '' '' ''
python3 journal_eingabe_neu.py 05.01.2023 'Python csv file lesen und DB schreiben, Parallels installiert auf Mac mit Windows' '' '' ''
python3 journal_eingabe_neu.py 06.01.2023 'MacBook Parallels Windows Control-M installieren' '' '' ''
python3 journal_eingabe_neu.py 07.01.2023 'Kawasaki Interessent da, Mac/Win VCStudio mit Git, Elena tefoniert, Mühldorf Kaffee, TopGun' '' '' ''
python3 journal_eingabe_neu.py 08.01.2023 'MacBook und Dell VritualBox mit Linux Mint, Kawasaki verkauft, Forstners essen' '' '' ''
python3 journal_eingabe_neu.py 09.01.2023 'Versuch Control-M auf DELL/Mint zu insnstallieren, Elena Hausbesuch, Ubuntu installiert Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''
python3 journal_eingabe_neu.py 10.01.2023 'Linux Mint, Roseline Sex' '' '' ''
python3 journal_eingabe_neu.py 11.01.2023 'Had-Eck Dyno gebracht' '' '' '' ''
python3 journal_eingabe_neu.py 12.01.2023 'Stütz, Katzenbuckel, seitliche Übungen, situps'  '' ''
python3 journal_eingabe_neu.py 13.01.2023 'Burger King Dorfen' '' '' ''
python3 journal_eingabe_neu.py 14.01.2023 'Roselione Sex, Freising gefahren' '' '' ''
python3 journal_eingabe_neu.py 15.01.2023 '' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''
python3 journal_eingabe_neu.py 16.01.2023 '' '' '' ''			
python3 journal_eingabe_neu.py 17.01.2023 'Kawasaki abmelden' '' ''  ''
python3 journal_eingabe_neu.py 18.01.2023 'Python Buch'	 '' '' ''
python3 journal_eingabe_neu.py 19.01.2023 'Roseline Sex' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''	
python3 journal_eingabe_neu.py 20.01.2023 'Python Übungen'  '' '' ''	
python3 journal_eingabe_neu.py 21.01.2023 'Roseline Sex' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''
python3 journal_eingabe_neu.py 22.01.2023 'Kawasaki verkauft und abgeholt, Forstner essen in Taufkirchen'  '' '' ''		
python3 journal_eingabe_neu.py 23.01.2023 '' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''	
python3 journal_eingabe_neu.py 24.01.2023 'PyCharm installation' ''	 '' ''	
python3 journal_eingabe_neu.py 25.01.2023 'MFT und SAP migration' 'Stütz, Katzenbuckel, seitliche Übungen, situps, Kettlebell start'  '' ''	
python3 journal_eingabe_neu.py 26.01.2023 'MFT und SAP migration' 'Kettlebell Minimal Übungen'	 '' ''
python3 journal_eingabe_neu.py 27.01.2023 'MFT und SAP migration, LibreOffice Dell installieren' '' '' ''
python3 journal_eingabe_neu.py 28.01.2023 'Roseline Sex, LibreOffice auf Macbook installiert, WS gefahren, keine Pfeife geraucht' 'Stütz, Katzenbuckel, seitliche Übungen, Kettlebell Video alle 3mal'	 '' ''
python3 journal_eingabe_neu.py 29.01.2023 'Keine Pfeife geraucht' 'Kettlebell Übungen'  '' ''
python3 journal_eingabe_neu.py 20.01.2023 'SAP Migration, keine Pfeife geraucht' '' '' ''
python3 journal_eingabe_neu.py 31.01.2023 'SAP und MFT migration, Steuerrückzahlung 2021, Keine Pfeife geraucht, Zigarillo gepafft' 'Kettlebell Übungen' '' ''
python3 journal_eingabe_neu.py 01.02.2023 'MFT,SAP migration, Dietrich Control-M Schulung, TS Angie Deluxen' '' 'TS war verschwendetes Geld, bekommt keinen hoch und die Bilder sind total veraltet'	
python3 journal_eingabe_neu.py 02.02.2023 'MFT,SAP migration, Dörr Untersuchungsergebnis, Hannover-Erding fahren' '' '' ''
python3 journal_eingabe_neu.py 03.02.2023 'MFT, SAP migration, Dietrich Control-M Schulung' '' '' ''
python3 journal_eingabe_neu.py 04.02.2023 'Roseline Sex, Waldkraiburg C&A, Mühldorf, Lethal Weapon 1' 'Stütz, Kettlebell' '' ''
python3 journal_eingabe_neu.py 05.02.2023 'Lethal Weapon 2' '' '' '' 
python3 journal_eingabe_neu.py 06.02.2023 'MFT, SAP migration, Dietrich Control-M Schulung,Lethal Weapon 3' 'Stütz, seitliche Übungen,Kettlebell' '' '' 
python3 journal_eingabe_neu.py 07.02.2023 'MFT, SAP migration ,Lethal Weapon 4' '' '' ''
python3 journal_eingabe_neu.py 08.02.2023 'MFT, SAP migration, KFC Parsdorf' '' '' ''
python3 journal_eingabe_neu.py 09.02.2023 'MFT, SAP migration' 'Stütz, Katzenbuckel, seitliche Übungen, Kettlebell' '' '' 
python3 journal_eingabe_neu.py 10.02.2023 'MFT, SAP migration, Ulli mail als Sandra wg 3er' '' '' ''
python3 journal_eingabe_neu.py 11.02.2023 'Roseline Sex, München fahren' '' '' ''
python3 journal_eingabe_neu.py 12.02.2023 'Erkältung' '' '' '' 
python3 journal_eingabe_neu.py 13.02.2023 'Standesamt 150,00 Euro , MFT, SAP migration' '' '' ''
python3 journal_eingabe_neu.py 14.02.2023 'MFT, SAP Migration, ED - AB - Gambach fahren' '' '' ''
python3 journal_eingabe_neu.py 15.02.2023 'Control-M Tag in FFM, FFM-AB-ED fahren' '' '' ''
python3 journal_eingabe_neu.py 16.02.2023 'MFT, SAP Migration, Sichtschutz Balkon entfernt' '' '' ''
python3 journal_eingabe_neu.py 17.02.2023 'Roseline sex, MFT, SAP Migration' '' '' ''
python3 journal_eingabe_neu.py 18.02.2023 'Ebersberg Kaffee, Chiemsee' 'Kettlebell' '' ''
python3 journal_eingabe_neu.py 19.02.2023 '' 'Kettlebell' '' '' 
python3 journal_eingabe_neu.py 20.02.2023 'MFT, SAP Migration' '' '' ''
python3 journal_eingabe_neu.py 21.02.2023 'MFT, SAP Migration' '' '' ''
python3 journal_eingabe_neu.py 22.02.2023 'Letzter Arbeitstag ivv' '' '' ''
python3 journal_eingabe_neu.py 23.02.2023 'Roseline Sex, FLSTFI fahren, Dorfen Kaffee eat & meet' 'Stütz, Kettlebell' '' ''
python3 journal_eingabe_neu.py 24.02.2023 'FLSTFI fahren, Dateien auf MacBook' 'Kettlebell, situps mit Gewicht' '' ''
python3 journal_eingabe_neu.py 25.02.2023 'Roseline Sex, München fahren' '' '' ''
python3 journal_eingabe_neu.py 26.02.2023 '' 'einmal Stütz, Kettlebell, situps mit Gewicht' '' ''
python3 journal_eingabe_neu.py 27.02.2023 '' 'Kettlebell' '' ''
python3 journal_eingabe_neu.py 28.02.2023 'ED - AB - Gambach fahren' '' '' ''
python3 journal_eingabe_neu.py 01.03.2023 'FFM mit Zug fahren' 'Kettlebell' '' ''
python3 journal_eingabe_neu.py 02.03.2023 'John Doe Flörsheim, Grosser Feldberg gefahren, BG heisser Chat' ' ' '' ''
python3 journal_eingabe_neu.py 03.03.2023 'Gambach-AB-ED fahren, WÜ Landstrasse' ' ' '' ''
python3 journal_eingabe_neu.py 04.03.2023 'Roseline Sex, Dostojewski' 'Kettlebell' '' ''
python3 journal_eingabe_neu.py 05.03.2023 'Fabi Geburtstag, Forstner Kaffee' '' '' 'Tanjas Mutter heiß, Denke an Sandra'
python3 journal_eingabe_neu.py 06.03.2023 ' ' 'Kettlebell, situps mit Kettlebell' '' 'Denke an Sandra zu spüren, berühren'
python3 journal_eingabe_neu.py 07.03.2023 'Roseline Sex, Geld eingezahlt MB, Schliersee Milchhäusl' 'Kettlebell+' '' 'Denke an Sandra, sie berühren, sie spüren'
python3 journal_eingabe_neu.py 08.03.2023 'LA gefahren, Döner essen, Tchibo Tasse & Filter' '' '' 'Immer wieder an Sandra denken'
python3 journal_eingabe_neu.py 09.03.2023 'Roseline Sex' 'Stütz, Bank' '' 'Sandra im Kopf'
python3 journal_eingabe_neu.py 10.03.2023 'Mühldorf Kaffee trinken' '' '' 'wie es wäre Sandra zu spüren'
python3 journal_eingabe_neu.py 11.03.2023 '' 'Bank, Stütz, Kettlebell-' '' 'Denke daran Sandra spüren und berühren, Sex mit Birgit'
python3 journal_eingabe_neu.py 12.03.2023 'Freising Stoffmarkt' '' '' 'Denke daran Sandra spüren und berühren, Sex mit Birgit'
python3 journal_eingabe_neu.py 13.03.2023 'Roseline Sex, FLHTKL Vilsbiburg Mareis' 'Bank, Stütz, seitliche Übungen, Kettlebell' '' 'Denke an Sandra spüren & berühren, Sex mit Birgit'
python3 journal_eingabe_neu.py 14.03.2023 'Mammut Schuhe bestellt, Roseline Zahnarzt' '' '' 'Denke daran Sandra spüren und berühren, denke an Sex mit Birgit'
python3 journal_eingabe_neu.py 15.03.2023 'Roseline Dr. Bloch, München fahren, Anhänger abgeholt' '' '' 'denke an Sex mit Sandra, an Sex mit Birgit'
python3 journal_eingabe_neu.py 16.03.2023 'Roseline Sex, FLHTKL fahren' 'Bank, Stütz, seitliche Übungen, Kettlebell' ''  'Denke an Sex mit Sandra, Sex mit Birgit'
python3 journal_eingabe_neu.py 17.03.2023 'FLSTFI fahren, VRSCDX fahren' 'Bank, Stütz, seitliche Übungen' '' 'Denke an Sex mit Sandra, Sex mit Birgit'
python3 journal_eingabe_neu.py 18.03.2023 'TÜV Termin ausgemacht, FLHTKL fahren Traunreut' '' '' 'Denke an Sex mit Sandra, Sex mit Birgit'
python3 journal_eingabe_neu.py 19.03.2023 'Roseline Sex, Kircheim Eis essen, IHlE Erding' 'Stütz, situp' '' 'Denke an Sex mit Sandra, Sex mit Birgit'
python3 journal_eingabe_neu.py 20.03.2023 'ED - Darmstadt fahren' '' '' ''
python3 journal_eingabe_neu.py 21.03.2023 'Darmstadt - AB fahren, Louis einkaufen, AB - ED fahren' '' '' 'Denke immer wieder an Sex mit Sandra, Sex mit Birgit'
python3 journal_eingabe_neu.py 22.03.2023 'Roseline Sex, FLHTKL und FLSTFI HU' '' '' 'Denke immer wieder an Sex mit Sandra, Sex mit Birgit'
python3 journal_eingabe_neu.py 23.03.2023 'FLHTKL fahren Maxlrain' 'Bank, Stütz, seitliche Übungen, situps' '' 'denke an CB; Sandra spüren; Birgit spüren'
python3 journal_eingabe_neu.py 24.03.2023 'Whatsapp Sandra' 'Bank, Stütz, seitliche Übungen' '' ''
python3 journal_eingabe_neu.py 25.03.2023 'Roseline Sex, ED Foot Markt' '' '' ''
python3 journal_eingabe_neu.py 26.03.2023 '' 'Bank' '' ''
python3 journal_eingabe_neu.py 27.03.2023 'Kino Film der vermessene Mensch' 'Bank, Stütz, situps' '' ''
python3 journal_eingabe_neu.py 28.03.2023 'FLSTFI, VRSCDV Had-Eck gebracht, Mareis Kaffee, Kuchen Vilsbiburg' '' '' ''
python3 journal_eingabe_neu.py 29.03.2023 'Roseline Sex, Pfannkuchen' 'Bank, Stütz, Sodbrennen' '' 'Denke an Sex mit Sandra'
python3 journal_eingabe_neu.py 30.03.2023 'Zahnarzt, Fossil Uhren bestellt' 'Bank, Stütz, seitliche Übungen' '' ''
python3 journal_eingabe_neu.py 31.03.2023 'ED nach AB und Köln fahren' '' '' ''
python3 journal_eingabe_neu.py 01.04.2023 '' 'Bank, Stütz, seitliche Übungen' '' ''
python3 journal_eingabe_neu.py 02.04.2023 '' 'Stütz' '' ''
python3 journal_eingabe_neu.py 03.04.2023 'REWE Köln Erster Arbeitstag' '' '' ''
python3 journal_eingabe_neu.py 04.04.2023 'REWE Köln' '' '' ''
python3 journal_eingabe_neu.py 05.04.2023 'REWE Köln' '' '' ''
python3 journal_eingabe_neu.py 06.04.2023 'REWE Köln' '' '' ''
python3 journal_eingabe_neu.py 07.04.2023 '' 'Stütz 150St' '' ''
python3 journal_eingabe_neu.py 08.04.2023 'Köln – ED fahren, Fossil Uhren Paket' '' '' ''
python3 journal_eingabe_neu.py 09.04.2023 'Roseline Sex' '' '' ''
python3 journal_eingabe_neu.py 10.04.2023 'FLHTKL fahren Wasserburg' 'Bank, Stütz, seitliche Übungen' '' ''
python3 journal_eingabe_neu.py 11.04.2023 'Fossil Uhr getragen, Roseline Fossil Uhr bestellt, RAV Pötzinger' 'Bank, Stütz' '' ''
python3 journal_eingabe_neu.py 12.04.2023 'RAV Pötzinger abgeholt' '' '' ''
python3 journal_eingabe_neu.py 13.04.2023 'Hilux Angebot' 'Stütz' '' ''
python3 journal_eingabe_neu.py 14.04.2023 'Dubliner essen' '' '' ''
python3 journal_eingabe_neu.py 15.04.2023 'Roseline Sex' 'Bank, Stütz, seitliche Übungen' '' ''
python3 journal_eingabe_neu.py 16.04.2023 'Kino John Wick 5' 'Bank, Stütz, seitliche Übungen 3*50, situps' '' ''
python3 journal_eingabe_neu.py 17.04.2023 'FLHTKL fahren' 'Bank, Stütz, seitliche Übungen 3*50, situps' '' ''
python3 journal_eingabe_neu.py 18.04.2023 'Roseline AB, Sandra telefoniert, Film Apocalypse Now' '' '' ''
python3 journal_eingabe_neu.py 19.04.2023 'Film Apocalypse Now, Solar Powerbank' '' '' ''
python3 journal_eingabe_neu.py 20.04.2023 'RestAPI arbeiten' 'Bank, Stütz, seitliche Übungen 3*50' '' ''
python3 journal_eingabe_neu.py 21.04.2023 'RestAPI arbeiten' '' '' ''
python3 journal_eingabe_neu.py 22.04.2023 'Roseline Sex, FLHTKL Straubing fahren' 'Bank, Stütz, seitliche Übungen 3*50' '' 'Denke an Sex mit Sandra'
python3 journal_eingabe_neu.py 23.04.2023 '' 'Bank, Stütz 3*50,  seitliche Übungen 2*50' '' ''
python3 journal_eingabe_neu.py 24.04.2023 'Udemy Kurs Linux Bootcamp' '' '' ''
python3 journal_eingabe_neu.py 25.04.2023 'Satzinger & Alice telefoniert, Udemy Kurs Linux Bootcamp' 'Bank 150' '' ''
python3 journal_eingabe_neu.py 26.04.2023 'Udemy Kurs Linux Bootcamp, Had-Eck' '' '' 'Sandra Chat'
python3 journal_eingabe_neu.py 27.04.2023 'Udemy Linux Bootcamp, Administration of Red Hat Linux 8,VRSCDX fahren' 'Bank, Stütz 3*50, situps' '' ''
python3 journal_eingabe_neu.py 28.04.2023 'Udemy Linux Bootcamp, Administration of Red Hat Linux 8, Roseline Babbel App und Udemy A1 Kurs' '' '' ''
python3 journal_eingabe_neu.py 29.04.2023 'Roseline Sex, Udemy Administration of Red Hat Linux 8,FLHTKL Frontenhausen, Gangkofen,Mühldorf' 'Bank, Stütz 2*50' '' 'Denke an Sex mit Sandra'
python3 journal_eingabe_neu.py 30.04.2023 'VRSCDX fahren mit GoPro' 'Bank, Stütz 1*50' '' ''
python3 journal_eingabe_neu.py 01.05.2023 'Sauerteig Brot backen' 'Bank, Stütz 3+50' '' ''
python3 journal_eingabe_neu.py 02.05.2023 'Udemy Administration of Red Hat Linux, Roseline AB, Linux Bootcamp' '' '' ''
python3 journal_eingabe_neu.py 03.05.2023 'Linux Bootcamp, BMC workshop, VRSCDX fahren' '' '' ''
python3 journal_eingabe_neu.py 04.05.2023 'BMC workshop, FLSTFI fahren und GoPro' 'Bank, Stütz 3*50' '' ''
python3 journal_eingabe_neu.py 05.05.2023 'FLSTFI fahren und GoPro, iPhone Rewe, Udemy Administration of Red Hat Linux, Linux Bootcamp' 'Bank 150' '' ''
python3 journal_eingabe_neu.py 06.05.2023 'VRSCDX fahren mit GoPro' '' '' ''
python3 journal_eingabe_neu.py 07.05.2023 'VRSCDX fahren mit GoPro - Rosenheim' 'Bank, Stütz 3*50' '' ''
python3 journal_eingabe_neu.py 08.05.2023 'Drohne DJI Air 2s geliefert, Probeflug OK, macht Spass' '' '' ''
python3 journal_eingabe_neu.py 09.05.2023 'VGH wg Arbeitszeugnis,Linux Bootcamp, Drohne DJI Air 2s draussen geflogen, Marc telefoniert' '' '' ''
python3 journal_eingabe_neu.py 10.05.2023 'McAfee auf Mac, Video schneiden mit GoPro Player, Linux Bootcamp' 'Bank, Stütz 3*50, situps' '' ''
python3 journal_eingabe_neu.py 11.05.2023 'Udemy Administration of Red Hat Linux, Linux Bootcamp' 'Bank,Stütz 1*50' '' ''
python3 journal_eingabe_neu.py 12.05.2023 'FLSTFI fahren, amadeus treffen' '' '' ''
python3 journal_eingabe_neu.py 13.05.2023 'Ampfing Baggerraceparty, Mühldorf, Udemy Administration of Red Hat Linux' '' '' ''
python3 journal_eingabe_neu.py 14.05.2023 'Vagrant auf AlmaLinux, Drohne am Krontahler Weiher, Ansible Video und auf MacBook' '' '' ''
python3 journal_eingabe_neu.py 15.05.2023 'Udemy Administration of Red Hat Linux Test' 'Bank, Stütz 3*50, seitliche Übungen 3*40' '' ''
python3 journal_eingabe_neu.py 16.05.2023 'Udemy BASH Programming, Version Control with Git' '' '' ''
python3 journal_eingabe_neu.py 17.05.2023 'Udemy BASH Programming, Dostojewski ED' 'Bank, Stütz, seitliche Übungen, 1*50, situps' '' ''
python3 journal_eingabe_neu.py 18.05.2023 'Roseline Sex, FLHKL fahren Landshut, vagrant VM gestartet' 'Bank 150' '' ''
python3 journal_eingabe_neu.py 19.05.2023 'VRSCDX fahren' 'Stütz 150, situps 100' '' ''
python3 journal_eingabe_neu.py 20.05.2023 'FLHTKL fahren mit GoPro' 'Stütz 150' '' ''
python3 journal_eingabe_neu.py 21.05.2023 'FLHTKL fahren mit Pro Thenner Weiher' 'Stütz 150' '' ''
python3 journal_eingabe_neu.py 22.05.2023 'Balkon Sichtschutz, Udemy: Version Control with Git, spazieren Indorf' '' '' ''
python3 journal_eingabe_neu.py 23.05.2023 'telefoniert mit Ben Stokes, spazieren Indorf' '' '' ''

python3 journal_eingabe_neu.py 24.05.2023 '' '' '' ''

python3 journal_eingabe_neu.py 25.05.2023 '' '' '' ''
python3 journal_eingabe_neu.py 26.05.2023 '' '' '' ''
python3 journal_eingabe_neu.py 27.05.2023 '' '' '' ''
python3 journal_eingabe_neu.py 28.05.2023 '' '' '' ''
python3 journal_eingabe_neu.py 29.05.2023 '' '' '' ''
python3 journal_eingabe_neu.py 30.05.2023 '' '' '' ''
python3 journal_eingabe_neu.py 31.05.2023 '' '' '' ''

python3 journal_eingabe_neu.py 01.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 02.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 03.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 04.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 05.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 06.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 07.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 08.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 09.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 10.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 11.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 12.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 13.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 14.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 15.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 16.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 17.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 18.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 19.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 20.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 21.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 22.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 23.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 24.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 25.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 26.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 27.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 8.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 29.06.2023 '' '' '' ''
python3 journal_eingabe_neu.py 30.06.2023 '' '' '' ''

alter table journalNew alter column erkenntnis type varchar (100);

update journalNew set erfolg ='Roseline AB, Sandra telefoniert, Film Apocalypse Now' where key =116 ;
update journalNew set erkenntnis ='Denke immer wieder an Sex mit Sandra, Sex mit Birgit' where key =92 ;

update depot set wert ='21.423,23' where key =67;
update depot set datum ='06.03.2023' where key =67;
#
update depot set wert ='20.951,82' where key =67;
update depot set datum ='11.03.2023' where key =67;




