#
python3 journal_eingabe_neu.py 22.12.2022 'Python programmieren, Hannover - Erding fahren, Sandra nach Erding gekommen' '' '' ''
python3 journal_eingabe_neu.py 23.12.2022 'Python und postgres' '' '' ''
python3 journal_eingabe_neu.py 24.12.2022 'ED - Gambach fahren' '' '' ''
python3 journal_eingabe_neu.py 25.12.2022 ' ' '' '' ''
python3 journal_eingabe_neu.py 26.12.2022 'Gambach - Köln fahren' '' '' ''
python3 journal_eingabe_neu.py 27.12.2022 'Python und postgres' '' '' ''
python3 journal_eingabe_neu.py 28.12.2022 'einkaufen, Roseline Sex' '' '' ''
python3 journal_eingabe_neu.py 29.12.2022 'Python und Postgres' '' '' ''
python3 journal_eingabe_neu.py 30.12.2022 'Python und Postgres, Visual Studio Code in Git' '' ''  ''
python3 journal_eingabe_neu.py 31.12.2022 'Python und Postgres, Visual Studio Code in Git' '' '' ''
python3 journal_eingabe_neu.py 01.01.2023 'Köln nach Erding fahren, Roseline WoZi Sex' '' '' ''
python3 journal_eingabe_neu.py 02.01.2023 'Python, Postgrers, Visual Studio Code auf MacBook, Forstner Essen Wartenbaerg Stütz, Katzenbuckel, seizliche Übungen, situps' '' ''
python3 journal_eingabe_neu.py 03.01.2023 'Python, VSCode auf Macbook Air' '' '' ''
python3 journal_eingabe_neu.py 04.01.2023 'Termin Standesamt' '' '' ''
python3 journal_eingabe_neu.py 05.01.2023 'Python csv file lesen und DB schreiben, Parallels installiert auf Mac mit Windows' '' '' ''
python3 journal_eingabe_neu.py 06.01.2023 'MacBook Parallels Windows Control-M installieren' '' '' ''
python3 journal_eingabe_neu.py 07.01.2023 'Kawasaki Interessent da, Mac/Win VCStudio mit Git, Elena tefoniert, Mühldorf Kaffee, TopGun' '' '' ''
python3 journal_eingabe_neu.py 08.01.2023 'MacBook und Dell VritualBox mit Linux Mint, Kawasaki verkauft, Forstners essen' '' '' ''
python3 journal_eingabe_neu.py 09.01.2023 'Versuch Control-M auf DELL/Mint zu insnstallieren, Elena Hausbesuch, Ubuntu installiert Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''
python3 journal_eingabe_neu.py 10.01.2023 'Linux Mint, Roseline Sex' '' '' ''
python3 journal_eingabe_neu.py 11.01.2023 'Had-Eck Dyno gebracht' '' '' '' ''
python3 journal_eingabe_neu.py 12.01.2023 'Stütz, Katzenbuckel, seitliche Übungen, situps'  '' ''
python3 journal_eingabe_neu.py 13.01.2023 'Burger King Dorfen' '' '' ''
python3 journal_eingabe_neu.py 14.01.2023 'Roselione Sex, Freising gefahren' '' '' ''
python3 journal_eingabe_neu.py 15.01.2023 '' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''
python3 journal_eingabe_neu.py 16.01.2023 '' '' '' ''			
python3 journal_eingabe_neu.py 17.01.2023 'Kawasaki abmelden' '' ''  ''
python3 journal_eingabe_neu.py 18.01.2023 'Python Buch'	 '' '' ''
python3 journal_eingabe_neu.py 19.01.2023 'Roseline Sex' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''	
python3 journal_eingabe_neu.py 20.01.2023 'Python Übungen'  '' '' ''	
python3 journal_eingabe_neu.py 21.01.2023 'Roseline Sex' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''
python3 journal_eingabe_neu.py 22.01.2023 'Kawasaki verkauft und abgeholt, Forstner essen in Taufkirchen'  '' '' ''		
python3 journal_eingabe_neu.py 23.01.2023 '' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''	
python3 journal_eingabe_neu.py 24.01.2023 'PyCharm installation' ''	 '' ''	
python3 journal_eingabe_neu.py 25.01.2023 'MFT und SAP migration' 'Stütz, Katzenbuckel, seitliche Übungen, situps, Kettlebell start'  '' ''	
python3 journal_eingabe_neu.py 26.01.2023 'MFT und SAP migration' 'Kettlebell Minimal Übungen'	 '' ''
python3 journal_eingabe_neu.py 27.01.2023 'MFT und SAP migration, LibreOffice Dell installieren' '' '' ''
python3 journal_eingabe_neu.py 28.01.2023 'Roseline Sex, LibreOffice auf Macbook installiert, WS gefahren, keine Pfeife geraucht' 'Stütz, Katzenbuckel, seitliche Übungen, Kettlebell Video alle 3mal'	 '' ''
python3 journal_eingabe_neu.py 29.01.2023 'Keine Pfeife geraucht' 'Kettlebell Übungen'  '' ''
python3 journal_eingabe_neu.py 20.01.2023 'SAP Migration, keine Pfeife geraucht' '' '' ''
python3 journal_eingabe_neu.py 31.01.2023 'SAP und MFT migration, Steuerrückzahlung 2021, Keine Pfeife geraucht, Zigarillo gepafft' 'Kettlebell Übungen' '' ''
python3 journal_eingabe_neu.py 01.02.2023 'MFT,SAP migration, Dietrich Control-M Schulung, TS Angie Deluxen' '' 'TS war verschwendetes Geld, bekommt keinen hoch und die Bilder sind total veraltet'	
python3 journal_eingabe_neu.py 02.02.2023 'MFT,SAP migration, Dörr Untersuchungsergebnis, Hannover-Erding fahren' '' '' ''
python3 journal_eingabe_neu.py 03.02.2023 'MFT, SAP migration, Dietrich Control-M Schulung' '' '' ''
python3 journal_eingabe_neu.py 04.02.2023 'Roseline Sex, Waldkraiburg C&A, Mühldorf, Lethal Weapon 1' 'Stütz, Kettlebell' '' ''
python3 journal_eingabe_neu.py 05.02.2023 'Lethal Weapon 2' '' '' '' 
python3 journal_eingabe_neu.py 06.02.2023 'MFT, SAP migration, Dietrich Control-M Schulung,Lethal Weapon 3' 'Stütz, seitliche ÜbungenKettlebell' '' '' 
python3 journal_eingabe_neu.py 07.02.2023 'MFT, SAP migration ,Lethal Weapon 4' '' '' ''
python3 journal_eingabe_neu.py 08.02.2023 'MFT, SAP migration, KFC Parsdorf' '' '' ''
python3 journal_eingabe_neu.py 09.02.2023 'MFT, SAP migration' 'Stütz, Katzenbuckel, seitliche Übungen, Kettlebell' '' '' 
python3 journal_eingabe_neu.py 10.02.2023 'MFT, SAP migration, Ulli mail als Sandra wg 3er' '' '' ''
python3 journal_eingabe_neu.py 11.02.2023 'Roseline Sex, München fahren' '' '' ''
python3 journal_eingabe_neu.py 12.02.2023 'Erkältung' '' '' '' 
python3 journal_eingabe_neu.py 13.02.2023 'Standesamt 150,00 Euro , MFT, SAP migration' '' '' ''
python3 journal_eingabe_neu.py 14.02.2023 'MFT, SAP Migration, ED - AB - Gambach fahren' '' '' ''
python3 journal_eingabe_neu.py 15.02.2023 'Control-M Tag in FFM, FFM-AB-ED fahren' '' '' ''
python3 journal_eingabe_neu.py 16.02.2023 'MFT, SAP Migration, Sichtschutz Balkon entfernt' '' '' ''
python3 journal_eingabe_neu.py 17.02.2023 'Roseline sex, MFT, SAP Migration' '' '' ''
python3 journal_eingabe_neu.py 18.02.2023 'Ebersberg Kaffee, Chiemsee' 'Kettlebell' '' ''
python3 journal_eingabe_neu.py 19.02.2023 '' 'Kettlebell' '' '' 
python3 journal_eingabe_neu.py 20.02.2023 'MFT, SAP Migration' '' '' ''
python3 journal_eingabe_neu.py 21.02.2023 'MFT, SAP Migration' '' '' ''
python3 journal_eingabe_neu.py 22.02.2023 'Letzter Arbeitstag ivv' '' '' ''
python3 journal_eingabe_neu.py 23.02.2023 'Roseline Sex, FLSTFI fahren, Dorfen Kaffee eat & meet' 'Stütz, Kettlebell' '' ''
python3 journal_eingabe_neu.py 24.02.2023 'FLSTFI fahren, Dateien auf MacBook' 'Kettlebell, situps mit Gewicht' '' ''
python3 journal_eingabe_neu.py 25.02.2023 'Roseline Sex, München fahren' '' '' ''
python3 journal_eingabe_neu.py 26.02.2023 '' 'einmal Stütz, Kettlebell, situps mit Gewicht' '' ''
python3 journal_eingabe_neu.py 27.02.2023 '' 'Kettlebell' '' ''
python3 journal_eingabe_neu.py 28.02.2023 'ED - AB - Gambach fahren' '' '' ''
python3 journal_eingabe_neu.py 01.03.2023 'FFM mit Zug fahren' 'Kettlebell' '' ''
python3 journal_eingabe_neu.py 02.03.2023 'John Doe Flörsheim, Grosser Feldberg gefahren, BG heisser Chat' ' ' '' ''
python3 journal_eingabe_neu.py 03.03.2023 'Gambach-AB-ED fahren, WÜ Landstrasse' ' ' '' ''
python3 journal_eingabe_neu.py 04.03.2023 'Roseline Sex, Dostojewski' 'Kettlebell' '' ''
python3 journal_eingabe_neu.py 05.03.2023 'Fabi Geburtstag, Forstner Kaffee' '' '' 'Tanjas Mutter heiß, Denke an Sandra'
python3 journal_eingabe_neu.py 06.03.2023 ' ' 'Kettlebell, situps mit Kettlebell' '' 'Denke an Sandra zu spüren, berühren'
python3 journal_eingabe_neu.py 07.03.2023 'Roseline Sex, Geld eingezahlt MB, Schliersee Milchhäusl' 'Kettlebell+' '' 'Denke an Sandra, sie berühren, sie spüren'
python3 journal_eingabe_neu.py 08.03.2023 'LA gefahren, Döner essen, Tchibo Tasse & Filter' '' '' 'Immer wieder an Sandra denken'

python3 journal_eingabe_neu.py 09.03.2023 'Roseline Sex' 'Stütz, Bank' '' ''

python3 journal_eingabe_neu.py 10.03.2023 '' '' '' ''
python3 journal_eingabe_neu.py 11.03.2023 '' '' '' ''
python3 journal_eingabe_neu.py 12.03.2023 '' '' '' ''
python3 journal_eingabe_neu.py 13.03.2023 '' '' '' ''
python3 journal_eingabe_neu.py 14.03.2023 '' '' '' ''
python3 journal_eingabe_neu.py 15.03.2023 '' '' '' ''
python3 journal_eingabe_neu.py 16.03.2023 '' '' '' ''
python3 journal_eingabe_neu.py 17.03.2023 '' '' '' ''
python3 journal_eingabe_neu.py 18.03.2023 '' '' '' ''
python3 journal_eingabe_neu.py 19.03.2023 '' '' '' ''

update journalNew set erfolg ='John Doe Flörsheim, Grosser Feldberg gefahren, BG heisser Chat' where key =68;

update depot set wert ='21.423,23' where key =67;
update depot set datum ='06.03.2023' where key =67;
