#python3 journal_eingabe_neu.py 15.01.2023 '' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''
#python3 journal_eingabe_neu.py 16.01.2023 '' '' '' ''			
#python3 journal_eingabe_neu.py 17.01.2023 'Kawasaki abmelden' '' ''		
#python3 journal_eingabe_neu.py 18.01.2023 'Python Buch'	 '' ''	
#python3 journal_eingabe_neu.py 19.01.2023 'Roseline Sex' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''	
#python3 journal_eingabe_neu.py 20.01.2023 'Python Übungen'  '' '' ''	
#python3 journal_eingabe_neu.py 21.01.2023 'Roseline Sex' 'Stütz, Katzenbuckel, seitliche Übungen, situps'	 '' ''
#python3 journal_eingabe_neu.py 22.01.2023 'Kawasaki verkauft und abgeholt, Forstner essen in Taufkirchen'  '' '' ''		
#python3 journal_eingabe_neu.py 23.01.2023 '' 'Stütz, Katzenbuckel, seitliche Übungen, situps' '' ''	
#python3 journal_eingabe_neu.py 24.01.2023 'PyCharm installation' ''	 '' ''	
#python3 journal_eingabe_neu.py 25.01.2023 'MFT und SAP migration' 'Stütz, Katzenbuckel, seitliche Übungen, situps, Kettlebell start'  '' ''	
#python3 journal_eingabe_neu.py 26.01.2023 'MFT und SAP migration' 'Kettlebell Minimal Übungen'	 '' ''

python3 journal_eingabe_neu.py 26.01.2023 '27. Januar 2023	'MFT und SAP migration, LibreOffice Dell installieren' ''	 '' ''
python3 journal_eingabe_neu.py 26.01.2023 '28. Januar 2023	'Roseline Sex, LibreOffice auf Macbook installiert, WS gefahren, keine Pfeife geraucht' '	Stütz, Katzenbuckel, seitliche Übungen, Kettlebell Video alle 3mal'	 '' ''
python3 journal_eingabe_neu.py 26.01.2023 '29. Januar 2023	'Keine Pfeife geraucht' '	Kettlebell Übungen'	 '' ''
python3 journal_eingabe_neu.py 26.01.2023 '30. Januar 2023	'SAP Migration, keine Pfeife geraucht' ''	 '' ''
python3 journal_eingabe_neu.py 26.01.2023 '31. Januar 2023	'SAP und MFT migration, Steuerrückzahlung 2021, Keine Pfeife geraucht, Zigarillo gepafft' '	Kettlebell Übungen'	 '' ''
python3 journal_eingabe_neu.py 26.01.2023 '1. Februar 2023	'MFT,SAP migration, Dietrich Control-M Schulung, TS Angie Deluxe Popcorn'	 '' 'TS war verschwendetes Geld, bekommt keinen hoch und die Bilder sind total veraltet'	
python3 journal_eingabe_neu.py 26.01.2023 '2. Februar 2023	'MFT,SAP migration, Dörr Untersuchungsergebnis, Hannover-Erding fahren' ''	 '' ''
python3 journal_eingabe_neu.py 26.01.2023 '3. Februar 2023	'MFT, SAP migration, Dietrich Control-M Schulung' ''	 '' ''
python3 journal_eingabe_neu.py 26.01.2023 '4. Februar 2023	'Roseline Sex, Waldkraiburg C&A, Mühldorf' 'Stütz, Kettlebell'	 '' ''
